<?php
/**
 * stockfoto-nik cms
 * 
 * Image view image index index template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the translate placeholder
$path = '_module_image_view_index_index';

$applicationName = $this->applicationData()->renderName();

$title = sprintf($this->translate('title' . $path), $applicationName);
$this->headTitle($title);
$description = sprintf($this->translate('meta_description_content' . $path), $applicationName);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);

?>
<header id="main-header">
    <h1>
        <?= sprintf($this->translate('main_heading' . $path), $applicationName) . "\n" ?>
    </h1>
</header>
<div class="row">
    <p class="col-md-6">
        <a href="<?= $this->url('image-upload', ['locale' => $this->locale(),]); ?>" title="<?= $this->translate('link_title' . $path . '_image_upload') ?>">
            <?= $this->translate('link' . $path . '_image_upload') . "\n" ?>
        </a>
    </p>
    <p class="col-md-6">
        <a href="<?= $this->url('image-show', ['locale' => $this->locale(),]); ?>" title="<?= $this->translate('link_title' . $path . '_image_show') ?>">
            <?= $this->translate('link' . $path . '_image_show') . "\n" ?>
        </a>
    </p>
</div>