<?php
/**
 * stockfoto-nik cms
 * 
 * User module view partial sing out navigationbar default template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */
?>
<div>
    <ul>
    <?php
        foreach ($this->container as $page) { 
    ?>
        <li>
        <?php
            if ($page->isActive()) {
        ?>
            <span class="active">
                <?= $this->translate($page->getLabel()) ?>
            </span>
        <?php
            } else {
        ?>
            <a href="<?= $page->getHref() ?>">
                <?= $this->translate($page->getLabel()) ?>
            </a>
        <?php
            }
        ?>
        </li>
    <?php
        }
    ?>
    </ul>
</div>