<?php
/**
 * stockfoto-nik cms
 * 
 * Application module view partial meta navigationbar default template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */
?>
<div id="meta-nav-wrapper">
    <ul id="meta-nav">
    <?php
        foreach ($this->container as $page) {
            if (!$this->navigation('meta_nav')->accept($page)) {
                continue; 
            } 
    ?>
        <li class="meta-nav-item">
        <?php
            if ($page->isActive()) {
        ?>
            <span class="active">
                <?= $this->translate($page->getLabel()) ?>
            </span>
        <?php
            } else {
        ?>
            <a class="meta-nav-link" href="<?= $page->getHref() ?>">
                <?= $this->translate($page->getLabel()) ?>
            </a>
        <?php
            }
        ?>
        </li>
    <?php
        }
    ?>
    </ul>
</div>