<?php
/**
 * stockfoto-nik cms
 * 
 * User auth login view template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the placeholder
$path = '_module_user_view_auth_login';

$applicationName = $this->applicationData()->renderName();

$title = sprintf($this->translate('title' . $path), $applicationName);
$this->headTitle($title);
$description = sprintf($this->translate('meta_description_content' . $path), $applicationName);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);

$form = $this->form;
$form->setAttribute('class', 'col-md-6');
$email = $form->get('email');
$password = $form->get('password');
$rememberMe = $form->get('remember_me');
$csrf = $form->get('login_csrf');
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn-success');
$form->prepare();
?>
<header id="main-header">
    <h1>
        <?= sprintf($this->translate('main_heading' . $path), $applicationName); ?>
    </h1>
</header>
<div class="row">
    <?= $this->form()->openTag($form) ?>
        <fieldset>
            <legend>
                <?= $this->translate('form_fieldset_legend' . $path) . "\n" ?>                
            </legend>
            <div class="form-elemet-wrapper">
                <?= $this->formLabel($email) ?>
                <?= $this->formElement($email) ?>
                <small id="email-description">
                    <i>
                        <?= $this->translate('form_email_description' . $path) . "\n" ?>
                    </i>
                </small>
                <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
            </div>
            <div class="form-elemet-wrapper">
                <?= $this->formLabel($password) ?>
                <?= $this->formElement($password) ?>
                <small id="password-description">
                    <i>
                        <?= $this->translate('form_password_description' . $path) . "\n" ?>
                    </i>
                </small>
                <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
            </div>
        </fieldset>
        <div class="form-elemet-wrapper-small">
            <?= $this->formElement($rememberMe) ?>
            <?= $this->formLabel($rememberMe) ?>
            <?= $this->formElementErrors()->render($rememberMe, ['class' => 'help-block']) ?>
        </div>
        <?= $this->formElement($csrf) ?>
        <div class="form-submit-wrapper">
            <?= $this->formSubmit($submit) ?>
        </div>
    <?= $this->form()->closeTag() ?>
</div>



    