<?php
/**
 * stockfoto-nik cms
 * 
 * User write-user add view template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the placeholder
$path = '_module_user_view_write-user_add';

$title = $this->translate('title' . $path);
$this->headTitle($title);
$description = $this->translate('meta_description_content' . $path);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);

$form = $this->form;
$form->setAttribute('class', 'col-md-6');
$alias = $form->get('alias');
$email = $form->get('email');
$password = $form->get('password');
$confirmPassword = $form->get('confirm_password');
$csrf = $form->get('login_csrf');
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn-success');
$form->prepare();
?>

<header id="main-header">
    <h1>
        <?= $this->translate('main_heading' . $path) ?>
    </h1>
    <p>
        Als Administrator können Sie hier einen Nutzer für diese Anwendung manuell hinzufügen.
    </p>
</header>
<div class="row">
    <?= $this->form()->openTag($form) ?>
        <fieldset>
            <legend>
                <?= $this->translate('form_fieldset_legend' . $path) . "\n" ?>                
            </legend>
            <div class="form-elemet-wrapper">
                <?= $this->formLabel($alias) ?>
                <?= $this->formElement($alias) ?>
                <small id="alias-description">
                    <i>
                        <?= $this->translate('form_alias_description' . $path) . "\n" ?>
                    </i>
                </small>
                <?= $this->formElementErrors()->render($alias, ['class' => 'help-block']) ?>
            </div>
            <div class="form-elemet-wrapper">
                <?= $this->formLabel($email) ?>
                <?= $this->formElement($email) ?>
                <small id="email-description">
                    <i>
                        <?= $this->translate('form_email_description' . $path) . "\n" ?>
                    </i>
                </small>
                <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
            </div>
            <div class="form-elemet-wrapper">
                <?= $this->formLabel($password) ?>
                <?= $this->formElement($password) ?>
                <small id="password-description">
                    <i>
                        <?= $this->translate('form_password_description' . $path) . "\n" ?>
                    </i>
                </small>
                <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
            </div>
            <div class="form-elemet-wrapper">
                <?= $this->formLabel($confirmPassword) ?>
                <?= $this->formElement($confirmPassword) ?>
                <small id="confirm-password-description">
                    <i>
                        <?= $this->translate('form_confirm_password_description' . $path) . "\n" ?>
                    </i>
                </small>
                <?= $this->formElementErrors()->render($confirmPassword, ['class' => 'help-block']) ?>
            </div>
        </fieldset>
        <?= $this->formElement($csrf) ?>
        <div class="form-submit-wrapper">
            <?= $this->formSubmit($submit) ?>
        </div>
    <?= $this->form()->closeTag() ?>
</div>