<?php
/**
 * stockfoto-nik cms
 * 
 * User write-user change-password view template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the placeholder
$path = '_module_user_view_write-user_change-password';

$title = $this->translate('title' . $path);
$this->headTitle($title);
$description = $this->translate('meta_description_content' . $path);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);

$form = $this->form;
$form->setAttribute('class', 'col-md-6');
$currentPassword = $form->get('current_password');
$newPassword = $form->get('new_password');
$confirmNewPassword = $form->get('confirm_new_password');
$csrf = $form->get('csrf');
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn-success');
$form->prepare();
?>
<header id="main-header">
    <h1>
        <?= $this->translate('main_heading' . $path) ?>      
    </h1>
</header>
<div class="row">
    <?= $this->form()->openTag($form) . "\n" ?>
        <div class="form-elemet-wrapper-small">
            <?= $this->formLabel($currentPassword) . "\n" ?>
            <?= $this->formElement($currentPassword) . "\n" ?>
            <small id="current-password-description">
                <i>
                    <?= $this->translate('form_current_password_description' . $path) . "\n" ?>
                </i>
            </small>
            <?= $this->formElementErrors()->render($currentPassword, ['class' => 'help-block']) . "\n" ?>
        </div>
        <div class="form-elemet-wrapper-small">
            <?= $this->formLabel($newPassword) . "\n" ?>
            <?= $this->formElement($newPassword) . "\n" ?>
            <small id="new-password-description">
                <i>
                    <?= $this->translate('form_new_password_description' . $path) . "\n" ?>
                </i>
            </small>
            <?= $this->formElementErrors()->render($newPassword, ['class' => 'help-block']) . "\n" ?>
        </div>
        <div class="form-elemet-wrapper-small">
            <?= $this->formLabel($confirmNewPassword) . "\n" ?>
            <?= $this->formElement($confirmNewPassword) . "\n" ?>
            <small id="confirm-password-description">
                <i>
                    <?= $this->translate('form-confirm-password-description' . $path) . "\n" ?>
                </i>
            </small>
            <?= $this->formElementErrors()->render($confirmNewPassword, ['class' => 'help-block']) . "\n" ?>
        </div>
        <?= $this->formElement($csrf) . "\n" ?>
        <div class="form-submit-wrapper">
            <?= $this->formSubmit($submit) . "\n" ?>
        </div>
        <p>
            <a href="<?= $this->url('user-account', ['locale' => $this->locale(),]) ?>" title="<?= $this->translate('link_title' . $path . '_cancel') ?>">
                <?= $this->translate('link' . $path . '_cancel') . "\n" ?>
            </a>
        </p>
    <?= $this->form()->closeTag() . "\n" ?>
</div>



