<?php
/**
 * stockfoto-nik cms
 * 
 * User write-user edit view template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the placeholder
$path = '_module_user_view_write-user_edit';

$title = $this->translate('title' . $path);
$this->headTitle($title);
$description = $this->translate('meta_description_content' . $path);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);

$user = $this->user;

$mainHeadig = $this
    ->escapeHtml(sprintf($this->translate('main_heading' . $path), $user->getEmail(), $user->getAlias()));

$form = $this->form->setAttribute('class', 'col-md-6');
$status = $form->get('status');
$roles = $form->get('roles')->setAttribute('class', 'multiselect-roles');;
$csrf = $form->get('csrf');
$submit = $form->get('submit')->setAttribute('class', 'btn-success');
$form->prepare();
?>
<header id="main-header">
    <h1>
        <?= $mainHeadig ?>
    </h1>
</header>
<div class="row">
    <?= $this->form()->openTag($form) . "\n" ?>
        <fieldset>
            <legend>
                <?= $this->translate('form_fieldset_legend' . $path) . "\n" ?>                
            </legend>
            <div class="form-elemet-wrapper">
                <?= $this->formLabel($status) ?>
                <?= $this->formSelect($status) ?>
                <small id="alias-description">
                    <i>
                        <?= $this->translate('form_status_description' . $path) . "\n" ?>
                    </i>
                </small>
                <?= $this->formElementErrors()->render($status, ['class' => 'help-block']) ?>
            </div>
            <div class="form-elemet-wrapper">
                <?= $this->formLabel($roles) ?>
                <?= $this->formSelect($roles) ?>
                <small id="alias-description">
                    <i>
                        <?= $this->translate('form_roles_description' . $path) . "\n" ?>
                    </i>
                </small>
                <?= $this->formElementErrors()->render($roles, ['class' => 'help-block']) ?>
            </div>
        </fieldset>
        <?= $this->formElement($csrf) . "\n" ?> 
        <div class="form-submit-wrapper">
            <?= $this->formSubmit($submit) . "\n" ?>
        </div>
        <p>
            <a href="<?= $this->url('read-user', ['locale' => $this->locale(), 'id' => $user->getId()]) ?>" title="<?= $this->translate('link_title' . $path . '_cancel') ?>">
                <?= $this->translate('link' . $path . '_cancel') . "\n" ?>
            </a>
        </p>
    <?= $this->form()->closeTag() . "\n" ?>
</div>