<?php
/**
 * stockfoto-nik cms
 * 
 * User write-user reset password view template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the placeholder
$path = '_module_user_view_write-user_reset-password';

$title = $this->translate('title' . $path);
$this->headTitle($title);
$description = $this->translate('meta_description_content' . $path);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);

$form = $this->form;
$form->setAttribute('class', 'col-md-6');
$email = $form->get('email');
$csrf = $form->get('csrf');
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn-success');

$form->prepare();

?>
<header id="main-header">
    <h1>
        <?= $this->translate('main_heading' . $path) ?>
    </h1>
</header>
<div class="row">
    <?= $this->form()->openTag($form) ?>
        <div class="form-elemet-wrapper-small">
            <?= $this->formLabel($email) ?>
            <?= $this->formElement($email) ?>
            <small id="email-description">
                <i>
                    <?= $this->translate('form_email_description' . $path) . "\n" ?>
                </i>
            </small>
            <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
        </div>
        <?= $this->formElement($csrf) ?>
        <div class="form-submit-wrapper">
            <?= $this->formSubmit($submit) ?>
        </div>
    <?= $this->form()->closeTag() ?>
</div>