<?php
/**
 * stockfoto-nik cms
 * 
 * Application module view laout segment flash messanger template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
    <button type="button" class="close-messages" data-dismiss="alert" aria-hidden="true">
    &times;
    </button>
    <ul class="messages-list"><li class="messages-list-item">')
    ->setMessageSeparatorString('</li><li class="messages-list-item">')
    ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error',   array('container', 'alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info',    array('container', 'alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('warning', array('container', 'alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('default', array('container', 'alert', 'alert-dismissible', 'alert-default'));
echo $flash->render('success', array('container', 'alert', 'alert-dismissible', 'alert-success'));