<?php
/**
 * stockfoto-nik cms
 * 
 * Application module view laout segment navigation template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */
?>
<div id="nav-wrapper">
    <nav id="main-nav">
        <?= $this->navigation('main_nav')->menu()
            ->setPartial('partials/nav-bars/main_default.phtml')->render(); ?>
        <?php
        if ($this->identity()) {
            echo $this->navigation('sing_out_nav')->menu()
                ->setPartial('partials/nav-bars/sing_out.phtml')->render();
        } else {
            echo $this->navigation('sing_in_nav')->menu()
                ->setPartial('partials/nav-bars/sing_in.phtml')->render();
        }
        ?>
        <?= $this->render('components/locate_nav.phtml')?>
    </nav>
</div>