<?php
/**
 * stockfoto-nik cms
 * 
 * Application module view laout segment navigation template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */
$mainNavBar = $this->navigation('main_nav')->menu()
    ->setPartial('partials/nav-bars/main_default.phtml');
?>
<div id="nav-wrapper">
    <nav id="main-nav">
        <?= $mainNavBar->render(); ?>
        <?= $this->render('components/locate_nav.phtml')?>
    </nav>
</div>