<?php
/**
 * stockfoto-nik cms
 * 
 * Application module view laout segment site-header template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

$brandNav = $this->navigation('brand_nav')->menu()
    ->setPartial('partials/nav-bars/brand_default.phtml');
?>
<header id="site-header">
    <div class="container">
        <?= $brandNav->render(); ?>
    </div>
</header>
