<?php
/**
 * stockfoto-nik cms
 * 
 * Application module view laout segment site-footer template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */
$metaNavBar = $this->navigation('meta_nav')->menu()
  ->setPartial('partials/nav-bars/meta_default.phtml');
?>
<footer id="site-footer">
    <?= $metaNavBar->render() ?>
    <small id="copyright-notice">
        &copy; 2018 - <?= date('Y') ?> Niklaus Höpfner
    </small>
</footer>