<?php
/**
 * stockfoto-nik cms
 * 
 * Application module view partial main navigationbar default template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */
?>
<button id="main-nav-toggler" type="button" data-toggle="collapse" data-target="#main-nav-list-wrapper" aria-controls="main-nav-list-wrapper" aria-expanded="false" aria-label="Toggle navigation">
    <span id="main-nav-toggler-icon"></span>
</button>
<div id="main-nav-list-wrapper" class="collapse">
    <ul id="main-nav-list">
    <?php
        foreach ($this->container as $page) {
            if (!$this->navigation('main_nav')->accept($page))
            {
                continue;  
            }
            if (!$page->hasPages()) {
    ?>
        <li class="main-nav-list-item">
    <?php
                if ($page->isActive()) {
    ?>
            <span class="active">
                <?=  $this->translate($page->getLabel()) ?>
            </span>
    <?php
                } else {
    ?>
            <a href="<?= $page->getHref() ?>">
                <?=  $this->translate($page->getLabel()) ?>
            </a>
    <?php
                }
    ?>
        </li>
    <?php
            } else {
    ?>
        <li class="main-nav-list-item-dropdown">
            <a id="<?= $page->getId() ?>" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <?= $this->translate($page->getLabel()) . ' &darr;' ?>
            </a>
            <ul class="dropdown-menu" aria-labelledby="<?= $page->getId() ?>">
            <?php
                foreach ($page->getPages() as $child) {
                    if (!$this->navigation()->accept($child)) {
                        continue;
                    }
            ?>
                <li class="dropdown-item">
                <?php
                    if ($child->isActive()) {
                ?>
                    <span class="active">
                        <?= $this->translate($child->getLabel()) ?>
                    </span>
                <?php
                    } else {
                ?>
                    <a href="<?= $child->getHref() ?>">
                        <?= $this->translate($child->getLabel()) ?>
                    </a>
                <?php
                    }
                ?>
                </li>
            <?php       
                }
            ?>
            </ul>
        </li>
    <?php
            }
    ?>
    <?php
        }
    ?>
    </ul>
</div>