<?php
/**
 * stockfoto-nik cms
 * 
 * Application module view partial pagination control default navigation template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */
?>
<ul class="pagination">
<!-- To first page -->
    <li class="pagination-item">
<?php if ($this->first != $this->current): ?>
        <a href="<?= $this->url($this->route, ['locale' => $this->locale(), 'page' => $this->first]); ?>" aria-label="First">
            &lt;&lt;
        </a>
<?php else: ?>
        <span>
            &lt;&lt;
        </span>
<?php endif; ?>
    </li>
<!-- Previous page link -->
    <li class="pagination-item">
<?php if (isset($this->previous)): ?>
        <a href="<?= $this->url($this->route, ['locale' => $this->locale(), 'page' => $this->previous]); ?>" aria-label="Previous">
            &lt;
        </a>
<?php else: ?>
        <span>
            &lt;
        </span>
<?php endif; ?>
    </li>
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <li class="pagination-item">
    <?php if ($page != $this->current): ?>
        <a class="page-link" href="<?= $this->url($this->route, ['locale' => $this->locale(), 'page' => $page]); ?>">
            <?= $page ?>
        </a>
<?php else: ?>
        <span>
            <?= $page ?>
        </span>
<?php endif; ?>
    </li>
<?php endforeach; ?>
<!-- Next page link -->
    <li class="pagination-item">
<?php if (isset($this->next)): ?>
        <a href="<?= $this->url($this->route, ['locale' => $this->locale(), 'page' => $this->next]); ?>" aria-label="Next">
            &gt;
        </a>
<?php else: ?>
        <span>
            &gt;
        </span>  
<?php endif; ?>
    </li>
<!-- Last page link -->
    <li class="pagination-item">
<?php if ($this->last !=  $this->current): ?>
        <a href="<?= $this->url($this->route, ['locale' => $this->locale(), 'page' => $this->last]); ?>" aria-label="Last">            
            &gt;&gt;
        </a>
<?php else: ?>
        <span>
            &gt;&gt;
        </span>
<?php endif; ?>
    </li>
</ul>