<?php
/**
 * stockfoto-nik cms
 * 
 * Application module view partial brand default navigation template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

$homePage = $container->findOneBy('route', 'home');
$istActive = $homePage->isActive();
?>
<?php
if ($istActive) {
?> 
<span id="brand">
    <?= $homePage ?>
</span>
<?php
} else {
?>
<a id="brand" href="<?= $homePage->getHref(); ?>">
    <?= $homePage ?>
</a>
<?php
}
?>
