<?php
/**
 * stockfoto-nik cms
 * 
 * User read-user account view template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the placeholder
$path = '_module_user_view_read-user_account';

$applicationName = $this->applicationData()->renderName();

$title = $this->translate('title' . $path);
$this->headTitle($title);
$description = $this->translate('meta_description_content' . $path);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);
?>
<header id="main-header">
    <h1>
        <?= sprintf($this->translate('main_heading' . $path), $applicationName) . "\n" ?>
    </h1>
</header>
<section class="row">
    <div class="col-md-6">
        <h2>
            <?= $this->translate('heading_registration-data' . $path) . "\n" ?>            
        </h2>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_alias' . $path) . "\n" ?>                
            </div>
            <div class="col-sm-7">
                <?= $this->escapeHtml($this->user->getAlias()) . "\n" ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_email' . $path) . "\n" ?>
            </div>
            <div class="col-sm-7">
                <?= $this->escapeHtml($this->user->getEmail()) . "\n" ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_password' . $path) . "\n" ?>
            </div>
            <div class="col-sm-7">
                <b>
                    &lowast;&lowast;&lowast;&lowast;&lowast;&lowast;&lowast;&lowast;&lowast;&lowast;&nbsp;&nbsp;
                </b>
                <a href="<?= $this->url('change-password', ['locale' => $this->locale(),]); ?>" title="<?= $this->translate('link_title_change-password' . $path) ?>">
                    <?= $this->translate('link_change-password' . $path) . "\n" ?>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_created-on' . $path) . "\n" ?>
            </div>
            <div class="col-sm-7">
                <?= $this->dateFormat(new DateTime($this->user->getCreatedOn()), IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, $this->locale()); ?>
            </div>
        </div>
    </div>
</section>
<section class="row">
    <div class="col-md-6">
        <h2>
            <?= $this->translate('heading_user-account-delete' . $path) . "\n" ?>            
        </h2>
        <a href="<?= $this->url('user-account-delete', ['locale' => $this->locale(),]); ?>" title="<?= $this->translate('link_title_user-account-delete' . $path) ?>">            
            <?= $this->translate('link_user-account-delete' . $path) . "\n" ?>
        </a>
    </div>
<?php
    if ($this->access('admin')) {
?>
    <div class="col-md-6">
        <h2>
            Admin-Nav
        </h2>
        <ul>
            <li>
                <a href="<?= $this->url('image-start', ['locale' => $this->locale(),]); ?>" title="<?= $this->translate('link_title_image_start' . $path) ?>">            
                    <?= $this->translate('link_image_start' . $path) . "\n" ?>
                </a>
            </li>
            <li>
                <a href="<?= $this->url('read-users', ['locale' => $this->locale(),]); ?>" title="<?= $this->translate('link_title_read_users' . $path) ?>">            
                    <?= $this->translate('link_read_users' . $path) . "\n" ?>
                </a>
            </li>
            <li>
                <a href="<?= $this->url('add-user', ['locale' => $this->locale(),]); ?>" title="<?= $this->translate('link_title_add_user' . $path) ?>">            
                    <?= $this->translate('link_add_user' . $path) . "\n" ?>
                </a>
            </li>
        </ul>
    </div>
<?php
    }
?>
</section>