<?php
/**
 * stockfoto-nik cms
 * 
 * User read-user detail view template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the placeholder
$path = '_module_user_view_read-user_detail';

$title = $this->translate('title' . $path);
$this->headTitle($title);
$description = $this->translate('meta_description_content' . $path);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);
?>
<header id="main-header">
    <h1>
        <?= $this->translate('main_heading' . $path) ?>
    </h1>
</header>
<section class="row">
    <div class="col-md-6">
        <h2>
            <?= $this->translate('heading_account-data' . $path) . "\n" ?>            
        </h2>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_alias' . $path) . "\n" ?>                
            </div>
            <div class="col-sm-7">
                <?= $this->escapeHtml($this->user->getAlias()) . "\n" ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_email' . $path) . "\n" ?>
            </div>
            <div class="col-sm-7">
                <?= $this->escapeHtml($this->user->getEmail()) . "\n" ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_password' . $path) . "\n" ?>
            </div>
            <div class="col-sm-7">
                <b>
                    &lowast;&lowast;&lowast;&lowast;&lowast;&lowast;&lowast;&lowast;&lowast;&lowast;&nbsp;&nbsp;
                </b>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_status' . $path) . "\n" ?>
            </div>
            <div class="col-sm-7">
            <?php
                if (0 === $this->user->getStatus()) {
                    echo $this->translate('value_status' . $path . '_blocked') . "\n";
                } else {
                    echo $this->translate('value_status' . $path . '_active') . "\n";
                }
            ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_created-on' . $path) . "\n" ?>
            </div>
            <div class="col-sm-7">
                <?= $this->dateFormat(new DateTime($this->user->getCreatedOn()), IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, $this->locale()) . "\n" ?>
            </div>
        </div>
    <?php
        if ($this->user->getUpdatedOn()) {
    ?>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_updated-on' . $path) . "\n" ?>
            </div>
            <div class="col-sm-7">
                <?= $this->dateFormat(new DateTime($this->user->getUpdatedOn()), IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, $this->locale()) . "\n" ?>
            </div>
        </div>
    <?php
        }
        if ($this->user->getRoles()) {
    ?>
        <div class="row">
            <div class="col-sm-5">
                <?= $this->translate('label_roles' . $path) . "\n" ?>
            </div>
            <div class="col-sm-7">
                <?php
                    echo implode(', ', $this->user->getRoles());
                ?>
            </div>
        </div>
    <?php
        }
    ?>
        <p>
            <a href="<?= $this->url('read-users', ['locale' => $this->locale(),]) ?>" title="<?= $this->translate('link_title' . $path . '_cancel') ?>">
                <?= $this->translate('link' . $path . '_cancel') . "\n" ?>
            </a>
        </p>
    </div>
    <div class="col-md-6">
        <h2>
            <?= $this->translate('heading_account-activities' . $path) . "\n" ?>            
        </h2>
        <ul>
            <li>
                <a href="<?= $this->url('edit-user', ['locale' => $this->locale(), 'id' => $this->user->getId()]) ?>" title="<?= $this->translate('link_title' . $path . '_update_account') ?>">                    
                    <?= $this->translate('link' . $path . '_update_account') . "\n" ?>
                </a>
            </li>
            <li>
                <a href="<?= $this->url('delete-user', ['locale' => $this->locale(), 'id' => $this->user->getId()]) ?>" title="<?= $this->translate('link_title' . $path . '_delete_account') ?>">                    
                    <?= $this->translate('link' . $path . '_delete_account') . "\n" ?>
                </a>
            </li>
        </ul>
    </div>
</section>