<?php
/**
 * stockfoto-nik cms
 * 
 * User read-user index view template (main content)
 * 
 * Template display the list of all users.
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the placeholder
$path = '_module_user_view_read-user_index';

$applicationName = $this->applicationData()->renderName();

$title = sprintf($this->translate('title' . $path), $applicationName);
$this->headTitle($title);
$description = sprintf($this->translate('meta_description_content' . $path), $applicationName);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);

$paginationControl = $this->paginationControl(
    $this->paginator,
    'Sliding',
    'partials/nav-bars/pagination_control_default.phtml',
    ['route' => 'read-users']
);
?>
<header id="main-header">
    <h1>
        <?= $this->translate('main_heading' . $path) ?>
    </h1>
</header>
<?php
foreach ($this->paginator as $user) {
?>
<section class="row">
    <div class="col-12">
        <h2>
            Konto-<?= $user->getId() . "\n" ?>
        </h2>
    </div>
    <div class="col-md-4">
        <?= $this->escapeHtml($user->getAlias()) . "\n" ?>
    </div>
    <div class="col-md-4">
        <?= $this->escapeHtml($user->getEmail()) . "\n" ?>
    </div>
    <div class="col-md-4">
        <a  href="<?= $this->url('read-user', ['locale' => $this->locale(), 'id' => $user->getId()]); ?>" title="<?= sprintf($this->translate('link_title' . $path . '_detail'), $user->getId()) ?>">
            <?= $this->translate('link' . $path . '_detail') . "\n"  ?>
        </a>
    </div>
</section>
<?php
}
?>
<div class="row">
    <?= $paginationControl . "\n" ?>
</div>
