<?php
/**
 * stockfoto-nik cms
 * 
 * Image view image remove index template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the translate placeholder
$path = '_module_image_view_remove_index';

$title = $this->translate('title' . $path);
$this->headTitle($title);
$description = $this->translate('meta_description_content' . $path);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);
// \Image\Form\RemoveForm
$form = $this->form;
$form->setAttribute('class', 'col-md');
$name = $form->get('name');
$csrf = $form->get('csrf');
$submitConfirm = $form->get('confirm');
$submitConfirm->setAttribute('class', 'btn-danger');
$submitCancel = $form->get('cancel');
$submitCancel->setAttribute('class', 'btn-primary');
$form->prepare();
?>
<header id="main-header">
    <h1>
        <?= $this->translate('main_heading' . $path) . "\n" ?>
    </h1>
    <p>
        <?= $this->translate('header_paragraph' . $path . '_remove') . "\n" ?>
    </p>
</header>
<section class="row">
    <div class="col-md">
        <h2>
            <?= $this->translate('heading' . $path . '_image_file') . "\n" ?>
        </h2>
        <figure>
            <img src="<?= $this->url('image-file', ['name'=> $this->name, 'thumbnail'=> true]); ?>" alt="<?= sprintf($this->translate('image_alt' . $path . '_image_file'), $this->name) ?>">
            <figcaption>
                <?= $this->name . "\n" ?>
            </figcaption>
        </figure>
    </div>
    <?= $this->form()->openTag($form) . "\n" ?>
        <fieldset>
            <legend>
                <?= $this->translate('legend' . $path . '_image_remove') . "\n" ?>                
            </legend>
            <?= $this->formElement($name) . "\n" ?>           
            <div class="form-elemet-wrapper">
                <?= $this->formSubmit($submitConfirm) . "\n" ?>
            </div> 
        </fieldset>
        <?= $this->formElement($csrf) . "\n" ?> 
        <div class="form-submit-wrapper">
            <?= $this->formSubmit($submitCancel) . "\n" ?>
        </div> 
    <?= $this->form()->closeTag() . "\n" ?>
</section>