<?php
/**
 * stockfoto-nik cms
 * 
 * Application module view partial application locate nav template
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

use Application\ValueObject\Data;

$locales = Data::MY_LOCALES;
$count = count($locales); // get int
?>
<?php
if (1 < $count) {
?>
<ul>
<?php
    foreach ($locales as $locale) {
        if (!null == $this->routeMatch()) {
            $name = $this->routeMatch()->getMatchedRouteName();
        } else {
            $name = 'home';
        }
        if ($locale != $this->locale()) {
?>
    <li>
        <a href="<?= $this->url($name, ['locale' => $locale]); ?>">
            <?= $locale ?>
        </a>
    </li>
<?php
        }
    }
?>
</ul>
<?php
}
?>