<?php
/**
 * stockfoto-nik cms
 * 
 * Homepage view template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

//Individual part of the translate placeholder
$path = '_module_application_view_index_index';

$applicationName = $this->applicationData()->renderName();

$title = sprintf($this->translate('title' . $path), $applicationName);
$this->headTitle($title);
$description = sprintf($this->translate('meta_description_content' . $path), $applicationName);
$keywords = $this->translate('meta_keywords_content' . $path);
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);
?>
<header>
    <h1>
        <?= sprintf($this->translate('main_heading' . $path), $applicationName) ?>
    </h1>
</header>