<?php
/**
 * stockfoto-nik cms
 * 
 * Homepage view template (main content)
 *  
 * @author     Niklaus Höpfner <editor@nik-web.net>
 * @link       https://github.com/nik-web/stockfoto-nik
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 * @version    1.0.0
 * @since      1.0.0
 */

$applicationName = $this->applicationData()->renderName();

$this->headTitle('Stockfotos vom ' . $applicationName);
$description = 'Sockfotografie von ' . $applicationName;
$keywords = 'Home, Startseite, Stockfoto, Foto, Bilder, Stockfotografie';
$this->headMeta()->appendName('description', $description)
    ->appendName('keywords', $keywords);
?>
<header>
    <h1>
        <?= 'Stockfotos bei ' . $applicationName ?>
    </h1>
</header>